Missing parentheses for print
```  File "c:\users\jose.torres\src\pyjs\pyjs\linker.py", line 303
    print "Module %r not found, sys.path is %r" % (mn, paths)
                                              ^
SyntaxError: invalid syntax```