Missing parentheses
```
pyjampiler loaded
Traceback (most recent call last):
  File ".\pyjampiler.py", line 19, in <module>
    import pyjs.translator
  File "\src\pyjs\pyjs\translator.py", line 15, in <module>
    from translator_proto import *
  File "\src\pyjs\pyjs\translator_proto.py", line 1130
    print 'attrib_join:', splitted, attr, word
                       ^
SyntaxError: invalid syntax
```