NameError: name 'long' is not defined
"Use int instead of long "
http://stackoverflow.com/a/14904834
six.PY2 for python 2 and six.PY3 for python 3 version detection
```
  File "c:\users\jose.torres\src\pyjs\pyjs\options.py", line 64, in Mappings
    _opt_types = {str: 'string', int: 'int', long: 'long',
NameError: name 'long' is not defined
```