Missing parentheses
```  File ".\pyjstest.py", line 418
    for test in test_pack['failed_list']:
                                        ^
SyntaxError: invalid syntax```