Missing parentheses around print
```  File ".\pyjampiler.py", line 115
    print "Compiling %s (%s)" % (module_name, based_filename)
                            ^
SyntaxError: invalid syntax```